# Start from a Java image.
FROM gradle:jdk21

# Set the working directory.
WORKDIR /app

# Copy the jar file into the Docker image.
COPY build/libs/basic_demo-0.1.0.jar .

# Expose the port.
EXPOSE 59001

# Run the jar file.
ENTRYPOINT ["java", "-cp", "basic_demo-0.1.0.jar", "basic_demo.ChatServerApp", "59001"]